name: shovill
description: Assemble bacterial isolate genomes from Illumina paired-end reads
keywords:
  - bacterial
  - assembly
  - illumina
tools:
  - shovill:
      description: Microbial assembly pipeline for Illumina paired-end reads
      homepage: https://github.com/tseemann/shovill
      documentation: https://github.com/tseemann/shovill/blob/master/README.md
      licence: ["GPL v2"]
      identifier: biotools:shovill
input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. [ id:'test', single_end:false ]
    - reads:
        type: file
        description: List of input paired-end FastQ files
output:
  - contigs:
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
          pattern: "contigs.fa"
      - ${meta.id}/shovill/contigs.fa:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
          pattern: "contigs.fa"
  - corrections:
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
          pattern: "shovill.corrections"
      - ${meta.id}/shovill/shovill.corrections:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
          pattern: "shovill.corrections"
  - log:
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
          pattern: "shovill.log"
      - ${meta.id}/shovill/shovill.log:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
          pattern: "shovill.log"
  - raw_contigs:
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
          pattern: "{skesa,spades,megahit,velvet}.fasta"
      - ${meta.id}/shovill/{skesa,spades,megahit,velvet}.fasta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
          pattern: "{skesa,spades,megahit,velvet}.fasta"
  - gfa:
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
          pattern: "contigs.{fastg,gfa,LastGraph}"
      - ${meta.id}/shovill/contigs.{fastg,gfa,LastGraph}:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
          pattern: "contigs.{fastg,gfa,LastGraph}"
  - versions:
      - ${meta.id}/shovill/versions.yml:
          type: file
          description: File containing software versions
          pattern: "versions.yml"
authors:
  - "@rpetit3"
maintainers:
  - "@rpetit3"
