name: bbmap_align
description: Align short or PacBio reads to a reference genome using BBMap
keywords:
  - align
  - map
  - fasta
  - fastq
  - genome
  - reference
tools:
  - bbmap:
      description: BBMap is a short read aligner, as well as various other bioinformatic
        tools.
      homepage: https://jgi.doe.gov/data-and-tools/bbtools/bb-tools-user-guide/
      documentation: https://jgi.doe.gov/data-and-tools/bbtools/bb-tools-user-guide/
      licence: ["UC-LBL license (see package)"]
      identifier: biotools:bbmap
input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. [ id:'test', single_end:false ]
    - fastq:
        type: file
        description: |
          List of input FastQ files of size 1 and 2 for single-end and paired-end data,
          respectively.
    - ref:
        type: file
        description: |
          Either "ref" a directory containing an index, the name of another directory
          with a "ref" subdirectory containing an index or the name of a fasta formatted
          nucleotide file containing the reference to map to.
output:
  - bam:
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
          pattern: "*.{bam}"
      - "*.bam":
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
          pattern: "*.{bam}"
  - txt:
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
      - bbmap_statistics.txt:
          type: file
          description: |
            File containing statistics from the BBMap alignment.
  - covstats:
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
      - bbmap_covstats.txt:
          type: file
          description: |
            File containing coverage statistics from the BBMap alignment.
  - versions:
      - versions.yml:
          type: file
          description: File containing software versions
          pattern: "versions.yml"
authors:
  - "@erikrikarddaniel"
maintainers:
  - "@erikrikarddaniel"
