name: bakta_bakta
description: Annotation of bacterial genomes (isolates, MAGs) and plasmids
keywords:
  - annotation
  - fasta
  - bacteria
tools:
  - bakta:
      description: Rapid & standardized annotation of bacterial genomes, MAGs & plasmids.
      homepage: https://github.com/oschwengers/bakta
      documentation: https://github.com/oschwengers/bakta
      tool_dev_url: https://github.com/oschwengers/bakta
      doi: "10.1099/mgen.0.000685"
      licence: ["GPL v3"]
      identifier: biotools:bakta
input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. [ id:'test', single_end:false ]
    - fasta:
        type: file
        description: |
          FASTA file to be annotated. Has to contain at least a non-empty string dummy value.
output:
  - embl:
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
          pattern: "*.embl"
      - ${prefix}.embl:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
          pattern: "*.embl"
  - faa:
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
          pattern: "*.faa"
      - ${prefix}.faa:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
          pattern: "*.faa"
  - ffn:
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
          pattern: "*.ffn"
      - ${prefix}.ffn:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
          pattern: "*.ffn"
  - fna:
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
          pattern: "*.fna"
      - ${prefix}.fna:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
          pattern: "*.fna"
  - gbff:
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
          pattern: "*.gbff"
      - ${prefix}.gbff:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
          pattern: "*.gbff"
  - gff:
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
          pattern: "*.gff3"
      - ${prefix}.gff3:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
          pattern: "*.gff3"
  - hypotheticals_tsv:
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
          pattern: "*.hypotheticals.tsv"
      - ${prefix}.hypotheticals.tsv:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
          pattern: "*.hypotheticals.tsv"
  - hypotheticals_faa:
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
          pattern: "*.hypotheticals.faa"
      - ${prefix}.hypotheticals.faa:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
          pattern: "*.hypotheticals.faa"
  - tsv:
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
          pattern: "*.tsv"
      - ${prefix}.tsv:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
          pattern: "*.tsv"
  - txt:
      - ${prefix}.txt:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
          pattern: "*.txt"
  - versions:
      - versions.yml:
          type: file
          description: File containing software versions
          pattern: "versions.yml"
authors:
  - "@rpetit3"
  - "@oschwengers"
  - "@jfy133"
maintainers:
  - "@rpetit3"
  - "@oschwengers"
  - "@jfy133"
