name: quast
description: Quality Assessment Tool for Genome Assemblies
keywords:
  - quast
  - assembly
  - quality
  - contig
  - scaffold
tools:
  - quast:
      description: |
        QUAST calculates quality metrics for genome assemblies
      homepage: http://bioinf.spbau.ru/quast
      doi: 10.1093/bioinformatics/btt086
      licence: ["GPL-2.0-only"]
      identifier: biotools:quast
input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. [ id:'test', single_end:false ]
    - fasta:
        type: file
        description: |
          The genome assembly to be evaluated. Has to contain at least a non-empty string dummy value.
output:
  - results:
      - ${meta.id}/quast/*:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
  - tsv:
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
          pattern: "${prefix}.tsv"
      - ${meta.id}/quast/report.tsv:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
          pattern: "${prefix}.tsv"
  - transcriptome:
      - meta:
          type: file
          description: |
            Report containing all the alignments of transcriptome to the assembly, only when a reference fasta is provided
          pattern: "${prefix}_transcriptome.tsv"
      - ${meta.id}/quast/contigs_reports/all_alignments_transcriptome.tsv:
          type: file
          description: |
            Report containing all the alignments of transcriptome to the assembly, only when a reference fasta is provided
          pattern: "${prefix}_transcriptome.tsv"
  - misassemblies:
      - meta:
          type: file
          description: |
            Report containing misassemblies, only when a reference fasta is provided
          pattern: "${prefix}_misassemblies.tsv"
      - ${meta.id}/quast/contigs_reports/misassemblies_report.tsv:
          type: file
          description: |
            Report containing misassemblies, only when a reference fasta is provided
          pattern: "${prefix}_misassemblies.tsv"
  - unaligned:
      - meta:
          type: file
          description: |
            Report containing unaligned contigs, only when a reference fasta is provided
          pattern: "${prefix}_unaligned.tsv"
      - ${meta.id}/quast/contigs_reports/unaligned_report.tsv:
          type: file
          description: |
            Report containing unaligned contigs, only when a reference fasta is provided
          pattern: "${prefix}_unaligned.tsv"
  - versions:
      - ${meta.id}/quast/versions.yml:
          type: file
          description: File containing software versions
          pattern: "versions.yml"
authors:
  - "@drpatelh"
  - "@kevinmenden"
maintainers:
  - "@drpatelh"
  - "@kevinmenden"
